### ISSUE TITLE
Should we keep the "undo clear" button and if so, what should we call it?

### ISSUE THREAD

**Issue by RolandMunsil** [RolandMunsil/Stepquencer#11]
(making this issue so all of our discussion of this is in one thread)

With the new saving/loading system, "clear" has now become "new song". If we kept the "undo clear" button, we'd have to rename it to something like "load unsaved song", "recover last song", etc.

Alternatively, we could get rid of "undo clear" and make it so that if the user clicks "new song" and they have unsaved changes, we show a popup and warn them.

Personally I'm not a huge fan of either option but I feel like the second is better. With "undo clear" it was pretty obvious to the user what it did, but with the new system it seems like there isn't a good, clear name for the button.
However I still don't like doing a popup because they're annoying and slow users down. For now I think its the better option tho. Maybe in the future we could have a "recover unsaved songs" menu, like in MS office apps (or like the recycle bin/trash bin in windows/mac) and cease warning the user before they lose unsaved data?

**Comment by gbrown3** [comment]
I agree that we should get rid of undo clear and have a popup, but I think having a popup is fine. Most saving systems have a sort of popup anyway to warn you about unsaved changes, and I think as long as we give users an option to disable that notification (i.e. "Save anyway and don't show me this again") we should be fine
