### ISSUE TITLE
Add ability to share songs with other users

### ISSUE THREAD

**Issue by RolandMunsil** [RolandMunsil/Stepquencer#7]
At the moment it looks like the best way to do this is via custom links. Here's some stuff I found that could be useful:
https://stackoverflow.com/questions/2095638/iphone-apps-can-i-open-an-app-from-a-link-in-a-website
https://xamarinhelp.com/uri-scheme/
https://riccardo-moschetti.org/2014/10/03/opening-a-mobile-app-from-a-link-the-xamarin-way-url-schemas/
https://forums.xamarin.com/discussion/12997/how-to-use-url-scheme-in-xamarin-ios

**Comment by gbrown3** [comment]
So we'll need a way to generate unique URLs for a given song? Maybe serialize the text file?

**Comment by RolandMunsil** [comment]
Yeah that's what I was thinking, have the url just essentially be something like "stepquencer://sharesong?song=\<insert text file but without newlines here\>"

**Comment by gbrown3** [comment]
I like it

**Comment by RolandMunsil** [comment]
Update: seems like custom scheme wont work, since most apps only recognize http://. I found a service called [Branch](https://branch.io/) that seems like it might work. They have a guide to getting it working with Xamarin here: https://github.com/BranchMetrics/xamarin-branch-deep-linking

Edit: it seems like Branch may be overcomplicated given what we want to do. It looks like it might be easier to just make a Github pages site that we link to that tries to redirect to our app.
