### ISSUE TITLE
Overwrite already saved songs

### ISSUE THREAD

**Issue by gbrown3** [RolandMunsil/Stepquencer#9]
I've noticed that a lot of people like to load up songs, improve them, and then want to save their work and overwrite their song. My proposal is this: we should keep track of the most recently loaded song, and if the user has loaded a song recently, there will be a third button on the savepage that says "Save to [song name here]"

**Comment by RolandMunsil** [comment]
Even better: what if we keep track of recently loaded song until they hit clear?

**Comment by gbrown3** [comment]
Update: might be fixed? Still needs testing to make sure
